# http://docs.travis-ci.com/user/languages/python/

language: python
python:
    - 3.6
    - 3.7
    - 3.8
#    - nightly # https://bugs.python.org/issue24934
    - pypy3

env:
    - DJANGO_VERSION=3.1

install:
    pip install django-bootstrap3 django-filer Django==$DJANGO_VERSION

script:
    python setup.py test

sudo: false
